### PR TITLE
RMSTRNG-908 abb driver for rws 1 0 is broken

### PR DESCRIPTION
**Pull request by krzyfre**
[Jira task](https://nomagic.atlassian.net/browse/RMSTRNG-908)

### How was the change tested?
rosrun nomagic_abb_driver nomagic_abb_driver-integration-test

### Review

_Review_: @mkatliar  
_Notify_: @_person2_

### CODE REVIEW

**Review by mkatliar — APPROVED** [review]
Thanks for the fix. Why did it work before?

**Comment by krzyfre** [comment]
Probably the thread where the exception was thrown was dying silently

**Comment by mkatliar** [comment]
> Probably the thread where the exception was thrown was dying silently

Then the whole process would die.

**Comment by mkatliar** [comment]
Ah, ok, it didn't die because we catch exceptions from `logout()` in `RWSClient::~RWSClient()`

**Pull request merged**
