### PR TITLE
GRASP-12948 Typo bugfix

### PR DESCRIPTION
**Pull request by Kotek13**
Fix of typo in rws_client.h.

Tested on hugo simulation in virtual machine.

### CODE REVIEW

**Review by krzyfre — APPROVED** [review]

**Comment by mkatliar** [comment]
How did it compile with that typo?

**Comment by Kotek13** [comment]
It did not. 
I must have made a mistake when replacing commit id of abb_librws in docker file as currently [it has to be done manually](https://github.com/NoMagicAi/monomagic/blob/4d8b2b4449154583878bc76517b32c7b34bf4fb9/gripper-ros/docker/gripper-ros/Dockerfile#L93).

**Comment by mkatliar** [comment]
> [it has to be done manually](https://github.com/NoMagicAi/monomagic/blob/4d8b2b4449154583878bc76517b32c7b34bf4fb9/gripper-ros/docker/gripper-ros/Dockerfile#L93).

There has been an issue for this for a long time: https://nomagic.atlassian.net/browse/DEVOPS-1981
But devops have not started working on it yet. Maybe you could push them as well?

**Comment by Kotek13** [comment]
Sure, i voted for the issue. There is really no mechanism now to detect such mistakes.
In the meantime I just prepared an alias command that changes the hash when I make changes on this repo so it won't happen to me again, but for newcomers like me there is not much information on how to prevent and watch out for such mistakes.

**Pull request merged**
